
APP_NAME = pcapng_listener
FLAGS = -O2

ROOT = ../..

MODULE_PCAP_DIR = $(ROOT)/sw_ethernet_tap/module_pcapng
INCLUDE += -I$(MODULE_PCAP_DIR)/src

include $(ROOT)/sc_xscope_support/host_library/makefile.shared

