#ifndef __AVB_TESTER_H__
#define __AVB_TESTER_H__

typedef enum {
  AVB_TESTER_EXPECT_NORMAL,
  AVB_TESTER_EXPECT_OVERSUBSCRIBED,
  AVB_TESTER_XSCOPE_PACKETS_ENABLE,
  AVB_TESTER_XSCOPE_PACKETS_DISABLE,
  AVB_TESTER_PRINT_DEBUG_ENABLE,
  AVB_TESTER_PRINT_DEBUG_DISABLE,
} tester_command_t;

#endif // __AVB_TESTER_H__
